export const Area = [
  {
    label: "亚洲",
    value: "asia",
    children: [
      { label: "阿富汗", value: "AF" },
      { label: "阿联酋", value: "AE" },
      { label: "阿曼", value: "OM" },
      { label: "孟加拉国", value: "BD" },
      { label: "不丹", value: "BT" },
      { label: "文莱", value: "BN" },
      { label: "柬埔寨", value: "KH" },
      { label: "中国", value: "CN" },
      { label: "印度", value: "IN" },
      { label: "印度尼西亚", value: "ID" },
      { label: "伊朗", value: "IR" },
      { label: "伊拉克", value: "IQ" },
      { label: "以色列", value: "IL" },
      { label: "日本", value: "JP" },
      { label: "约旦", value: "JO" },
      { label: "哈萨克斯坦", value: "KZ" },
      { label: "韩国", value: "KR" },
      { label: "科威特", value: "KW" },
      { label: "老挝", value: "LA" },
      { label: "黎巴嫩", value: "LB" },
      { label: "马来西亚", value: "MY" },
      { label: "马尔代夫", value: "MV" },
      { label: "蒙古", value: "MN" },
      { label: "缅甸", value: "MM" },
      { label: "尼泊尔", value: "NP" },
      { label: "阿曼", value: "OM" },
      { label: "巴基斯坦", value: "PK" },
      { label: "菲律宾", value: "PH" },
      { label: "卡塔尔", value: "QA" },
      { label: "沙特阿拉伯", value: "SA" },
      { label: "新加坡", value: "SG" },
      { label: "斯里兰卡", value: "LK" },
      { label: "叙利亚", value: "SY" },
      { label: "泰国", value: "TH" },
      { label: "东帝汶", value: "TL" },
      { label: "土耳其", value: "TR" },
      { label: "土库曼斯坦", value: "TM" },
      { label: "乌兹别克斯坦", value: "UZ" },
      { label: "越南", value: "VN" },
      { label: "台湾", value: "TW" },
    ],
  },
  {
    label: "非洲",
    value: "africa",
    children: [
      { label: "阿尔及利亚", value: "DZ" },
      { label: "安哥拉", value: "AO" },
      { label: "贝宁", value: "BJ" },
      { label: "博茨瓦纳", value: "BW" },
      { label: "布基纳法索", value: "BF" },
      { label: "布隆迪", value: "BI" },
      { label: "佛得角", value: "CV" },
      { label: "喀麦隆", value: "CM" },
      { label: "中非共和国", value: "CF" },
      { label: "乍得", value: "TD" },
      { label: "科摩罗", value: "KM" },
      { label: "刚果民主共和国", value: "CD" },
      { label: "刚果共和国", value: "CG" },
      { label: "科特迪瓦", value: "CI" },
      { label: "吉布提", value: "DJ" },
      { label: "埃及", value: "EG" },
      { label: "赤道几内亚", value: "GQ" },
      { label: "厄立特里亚", value: "ER" },
      { label: "埃塞俄比亚", value: "ET" },
      { label: "加蓬", value: "GA" },
      { label: "冈比亚", value: "GM" },
      { label: "加纳", value: "GH" },
      { label: "几内亚", value: "GN" },
      { label: "几内亚比绍", value: "GW" },
      { label: "肯尼亚", value: "KE" },
      { label: "莱索托", value: "LS" },
      { label: "利比里亚", value: "LR" },
      { label: "利比亚", value: "LY" },
      { label: "马达加斯加", value: "MG" },
      { label: "马拉维", value: "MW" },
      { label: "马里", value: "ML" },
      { label: "毛里求斯", value: "MU" },
      { label: "毛里塔尼亚", value: "MR" },
      { label: "摩洛哥", value: "MA" },
      { label: "莫桑比克", value: "MZ" },
      { label: "纳米比亚", value: "NA" },
      { label: "尼日尔", value: "NE" },
      { label: "尼日利亚", value: "NG" },
      { label: "卢旺达", value: "RW" },
      { label: "圣多美和普林西比", value: "ST" },
      { label: "塞内加尔", value: "SN" },
      { label: "塞舌尔", value: "SC" },
      { label: "塞拉利昂", value: "SL" },
      { label: "索马里", value: "SO" },
      { label: "南非", value: "ZA" },
      { label: "南苏丹", value: "SS" },
      { label: "苏丹", value: "SD" },
      { label: "斯威士兰", value: "SZ" },
      { label: "坦桑尼亚", value: "TZ" },
      { label: "多哥", value: "TG" },
      { label: "突尼斯", value: "TN" },
      { label: "乌干达", value: "UG" },
      { label: "赞比亚", value: "ZM" },
      { label: "津巴布韦", value: "ZW" },
    ],
  },
  {
    label: "欧洲",
    value: "europe",
    children: [
      { value: "AL", label: "阿尔巴尼亚" },
      { value: "AD", label: "安道尔" },
      { value: "AT", label: "奥地利" },
      { value: "BY", label: "白俄罗斯" },
      { value: "BE", label: "比利时" },
      { value: "BA", label: "波斯尼亚和黑塞哥维那" },
      { value: "BG", label: "保加利亚" },
      { value: "HR", label: "克罗地亚" },
      { value: "CY", label: "塞浦路斯" },
      { value: "CZ", label: "捷克" },
      { value: "DK", label: "丹麦" },
      { value: "EE", label: "爱沙尼亚" },
      { value: "FI", label: "芬兰" },
      { value: "FR", label: "法国" },
      { value: "DE", label: "德国" },
      { value: "GR", label: "希腊" },
      { value: "HU", label: "匈牙利" },
      { value: "IS", label: "冰岛" },
      { value: "IE", label: "爱尔兰" },
      { value: "IT", label: "意大利" },
      { value: "LV", label: "拉脱维亚" },
      { value: "LI", label: "列支敦士登" },
      { value: "LT", label: "立陶宛" },
      { value: "LU", label: "卢森堡" },
      { value: "MK", label: "马其顿" },
      { value: "MT", label: "马耳他" },
      { value: "MD", label: "摩尔多瓦" },
      { value: "MC", label: "摩纳哥" },
      { value: "ME", label: "黑山" },
      { value: "NL", label: "荷兰" },
      { value: "NO", label: "挪威" },
      { value: "PL", label: "波兰" },
      { value: "PT", label: "葡萄牙" },
      { value: "RO", label: "罗马尼亚" },
      { value: "RU", label: "俄罗斯" },
      { value: "SM", label: "圣马力诺" },
      { value: "RS", label: "塞尔维亚" },
      { value: "SK", label: "斯洛伐克" },
      { value: "SI", label: "斯洛文尼亚" },
      { value: "ES", label: "西班牙" },
      { value: "SE", label: "瑞典" },
      { value: "CH", label: "瑞士" },
      { value: "TR", label: "土耳其" },
      { value: "UA", label: "乌克兰" },
      { value: "UK", label: "英国" },
      { value: "VA", label: "梵蒂冈" },
    ],
  },
  {
    label: "北美洲",
    value: "north_america",
    children: [
      { value: "AG", label: "安提瓜和巴布达" },
      { value: "BS", label: "巴哈马" },
      { value: "BB", label: "巴巴多斯" },
      { value: "BZ", label: "伯利兹" },
      { value: "CA", label: "加拿大" },
      { value: "CR", label: "哥斯达黎加" },
      { value: "CU", label: "古巴" },
      { value: "DM", label: "多米尼加" },
      { value: "DO", label: "多米尼加共和国" },
      { value: "SV", label: "萨尔瓦多" },
      { value: "GD", label: "格林纳达" },
      { value: "GT", label: "危地马拉" },
      { value: "HT", label: "海地" },
      { value: "HN", label: "洪都拉斯" },
      { value: "JM", label: "牙买加" },
      { value: "MX", label: "墨西哥" },
      { value: "NI", label: "尼加拉瓜" },
      { value: "PA", label: "巴拿马" },
      { value: "PR", label: "波多黎各" },
      { value: "KN", label: "圣基茨和尼维斯" },
      { value: "LC", label: "圣卢西亚" },
      { value: "VC", label: "圣文森特和格林纳丁斯" },
      { value: "TT", label: "特立尼达和多巴哥" },
      { value: "US", label: "美国" },
    ],
  },
  {
    label: "中美洲",
    value: "central_america",
    children: [
      { value: "BZ", label: "伯利兹" },
      { value: "CR", label: "哥斯达黎加" },
      { value: "SV", label: "萨尔瓦多" },
      { value: "GT", label: "危地马拉" },
      { value: "HN", label: "洪都拉斯" },
      { value: "NI", label: "尼加拉瓜" },
      { value: "PA", label: "巴拿马" },
    ],
  },
  {
    label: "南美洲",
    value: "south_america",
    children: [
      { value: "AR", label: "阿根廷" },
      { value: "BO", label: "玻利维亚" },
      { value: "BR", label: "巴西" },
      { value: "CL", label: "智利" },
      { value: "CO", label: "哥伦比亚" },
      { value: "EC", label: "厄瓜多尔" },
      { value: "FK", label: "福克兰群岛" },
      { value: "GY", label: "圭亚那" },
      { value: "GF", label: "法属圭亚那" },
      { value: "PY", label: "巴拉圭" },
      { value: "PE", label: "秘鲁" },
      { value: "SR", label: "苏里南" },
      { value: "UY", label: "乌拉圭" },
      { value: "VE", label: "委内瑞拉" },
    ],
  },
  {
    label: "大洋洲",
    value: "oceania",
    children: [
      { value: "AU", label: "澳大利亚" },
      { value: "FJ", label: "斐济" },
      { value: "KI", label: "基里巴斯" },
      { value: "MH", label: "马绍尔群岛" },
      { value: "FM", label: "密克罗尼西亚" },
      { value: "NR", label: "瑙鲁" },
      { value: "NZ", label: "新西兰" },
      { value: "PW", label: "帕劳" },
      { value: "PG", label: "巴布亚新几内亚" },
      { value: "WS", label: "萨摩亚" },
      { value: "SB", label: "所罗门群岛" },
      { value: "TO", label: "汤加" },
      { value: "TV", label: "图瓦卢" },
      { value: "VU", label: "瓦努阿图" },
    ],
  },
];
